### ISSUE TITLE
Neo Theme turned from Blue to Black on Jenkins version - 2.340

### ISSUE THREAD

**Issue by athith-chammatira** [TobiX/jenkins-neo2-theme#108]
I upgraded the Jenkins to 2.340 and looks like the theme is NOT working now 👍 

![image](https://user-images.githubusercontent.com/47698857/159956535-535ee58f-837b-4685-abcc-a8254bb96c1d.png)

Turned Blue to Black. :)

**Comment by TeezeR-22** [comment]
To correct the problem, replace the "#header" with ".page-header" in style.less
![image](https://user-images.githubusercontent.com/45720987/160340990-f3bc7384-b7e7-4336-b387-56265b4957ac.png)

I changed the colors, but the theme works again
![image](https://user-images.githubusercontent.com/45720987/160341118-06e78673-2a52-492b-9e55-aa4a7ca92553.png)
