### ISSUE TITLE
Job build history left nav misaligned.

### ISSUE THREAD

**Issue by madelaney** [TobiX/jenkins-neo2-theme#11]
On Jenkins 2.121.3, when the `displayName` of a job wraps around, the `left-nav` div encroaches on the build icon.

![jenkins-neo-left-nav-overlay](https://user-images.githubusercontent.com/6340271/44858110-46783400-ac3f-11e8-8cd4-41037d38cbdf.png)

**Comment by ViceIce** [comment]
![image](https://user-images.githubusercontent.com/1798109/67078216-27b16580-f191-11e9-95cd-08a8d29329e7.png)

Same here

**Comment by ViceIce** [comment]
looks like the `multi-line` css class added by jenkins is the cause.
![image](https://user-images.githubusercontent.com/1798109/67078443-98f11880-f191-11e9-930f-965533d7e3f0.png)

**Comment by TobiX** [comment]
Isn't that the same as without the theme?
![grafik](https://user-images.githubusercontent.com/78534/96979044-46260b80-151f-11eb-85e2-9bb9514586c2.png)
Sure, the alignment is better, but the problem is basically the same...
