### ISSUE TITLE
Styling for dashboard-view portlets

### ISSUE THREAD

**Issue by luebbe** [TobiX/jenkins-neo2-theme#13]
Hi @TobiX,

tried out your version of the jenkins-neo2-theme. It looks great!
Right now the dashboard-view portlets are only partly styled. See screenshot:
![image](https://user-images.githubusercontent.com/3872576/51309261-48069500-1a44-11e9-9832-dd89626f6887.png)
Or is it just by chance that the green tick mark is shown correctly?

**Comment by TobiX** [comment]
That seems to be a general problem with 16x16 health icons...
