### ISSUE TITLE
Console text out of the box when using Parallel stages

### ISSUE THREAD

**Issue by m-mital** [TobiX/jenkins-neo2-theme#17]
Hi I'm using your themes. They're great. But recently I've noticed some annoying problem with the styles: 
![image](https://user-images.githubusercontent.com/7765376/70757956-afef5980-1d41-11ea-8d6b-b84d987af6e4.png)

It shows up only when you use Parallel stages. Their title is out of the console box.

**Comment by TobiX** [comment]
This is not a problem with my theme, the same thing happens in Jenkins without the theme.
