### ISSUE TITLE
New Jenkins design breaks search box icon placement at the header bar

### ISSUE THREAD

**Issue by juliohm1978** [TobiX/jenkins-neo2-theme#18]
Just upgraded Jenkins to 2.222 and the new header bar redisgn breaks the serch icon placement for this theme.

![image](https://user-images.githubusercontent.com/4145456/75589702-40dcf380-5a5a-11ea-9255-5acd1216c66e.png)

The search icon now overlaps with the typed text, making it difficult to read.

![image](https://user-images.githubusercontent.com/4145456/75589845-a6c97b00-5a5a-11ea-80f5-5211a221727a.png)

This seems to be caused by the header bar revamp in the latest version.

![image](https://user-images.githubusercontent.com/4145456/75589895-cc568480-5a5a-11ea-93b4-7ad0982e4523.png)

**Comment by TobiX** [comment]
I'm aware of that (see https://github.com/jenkinsci/jenkins/pull/4463#issuecomment-581990080), I just haven't got around to fixing it yet.

**Comment by TobiX** [comment]
Should be better now. Not perfect, but my CSS-fu is pretty rusty... Pull request fixing the icon color welcome...

**Comment by juliohm1978** [comment]
![image](https://user-images.githubusercontent.com/4145456/76170770-c9971600-6163-11ea-99e4-a25cd0543ad4.png)

Search lens icon is gone, but I'm really ok with this. Thank you!

**Comment by TobiX** [comment]
> Search lens icon is gone, but I'm really ok with this.

That was intended, since it was like that before: https://github.com/TobiX/jenkins-neo2-theme/blob/master/img/screenshot1.png
