### ISSUE TITLE
Font size errors in rendering Build Failure Analyzer output

### ISSUE THREAD

**Issue by toschder** [TobiX/jenkins-neo2-theme#19]
Hi, 
when rendering the output of the https://plugins.jenkins.io/build-failure-analyzer/ something goes wrong with the neo-theme.css. 
The font is too big and the output no more readable, see attached screenshot.

![image-2020-04-01-10-31-22-736](https://user-images.githubusercontent.com/20084319/78264279-44551600-7503-11ea-80a2-ba5e8333200c.png)

Can you please try to fix that?

Thx, Torsten

**Comment by TobiX** [comment]
That looks like a bogus `<h3>` tag somewhere, so I would take it up with the `build-failure-analyzer` if the aren't misusing header tags for text formatting somewhere...

Nevertheless, I'm not very happy with the look of `h3` headers in the theme as well, so I will change the layout of those a bit...

**Comment by swiatlyk** [comment]
I also facing this issue. I use a lot of h3 tags in my job descriptions. When do you plan to change this?

**Comment by swiatlyk** [comment]
Any update about this issue? When it will be fixed?
