### ISSUE TITLE
Neo2 theme doesn't work with pipeline editor

### ISSUE THREAD

**Issue by johnarnold** [TobiX/jenkins-neo2-theme#2]
Hi Tobi,

Thanks for your work on neo2 theme.  Mostly the theme works great, but there is one issue that persists.

When creating pipeline jobs, the job editor doesn't display text correctly.  The curser does not display in the correct position in the text box, it's always some spaces to the right of where you're actually editing.   this makes the editor basically unusable.

This issue was reported here:
https://issues.jenkins-ci.org/browse/JENKINS-36475
https://github.com/jenkins-contrib-themes/jenkins-neo-theme/issues/19

It seems that the ACE text editor plugin doesn't support non-monospaced fonts.   Is it possible to tweak your css so that it uses a monospace font when the class is ace_content, as suggested by @slide ?

Or can you think of another fix?

Thanks!

**Comment by johnarnold** [comment]
Hmm seems like you've already seen this issue.  Any idea why this commit doesn't fix it?
https://github.com/TobiX/jenkins-neo2-theme/commit/ab1d9d00d20d814c6681bb7bf4b278cf0e3ec360

**Comment by slide** [comment]
Is it possible that the files in dist don't have that fix? I cloned the repo and built the case myself, I'll test it out locally.

**Comment by TobiX** [comment]
Well, dist is built by Travis-CI after each commit, so should have that fix, and it's working on my own instances... I can also not reproduce the problem in a clean docker container:

1. Start container:
```
docker run -p 8080:8080 jenkins/jenkins
```
2. Select plugins (None, only pipeline)
3. Install simple theme plugin
4. Restart Jenkins
5. Set theme to `https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css`
6. Create new pipeline project

Editor works...

Maybe there is anything else breaking the style for the ACe editor?

**Comment by slide** [comment]
The editor can be typed in, but the cursor is offset from where the typing actually happens. I'll try with the docker as you have and verify.

**Comment by TobiX** [comment]
Yes, I know how the bug manifests, but I haven't seen it in my installations since I applied ab1d9d00d20d814c6681bb7bf4b278cf0e3ec360... At least on Windows 10 or Linux with Firefox... I just noticed the bug still occurs in Chrome, sorry. I'll look for a better fix.

**Comment by slide** [comment]
Thanks for looking into this more, it's a really nice theme and I definitely appreciate your work!

**Comment by johnarnold** [comment]
Fixed, thanks!
