### ISSUE TITLE
Search suggestions are always displayed in all caps

### ISSUE THREAD

**Issue by adjika** [TobiX/jenkins-neo2-theme#3]
Context:
Jenkins search bar

Should be:
Possible matches are suggested exactly the way they are written / known to jenkins.

Is:
Suggestions are always displayed in all caps.

Example screenshot:
A project/job known as "seed" to both jenkins internally as well as the user is suggested as "SEED".
![grafik](https://user-images.githubusercontent.com/29277957/32954477-82d19be8-cbb3-11e7-90ff-4a8da1ffe313.png)

**Comment by lajish** [comment]
@adjika 

You can fix this issue by removing _text-transform:uppercase;_ from css file.

Regards,
Lajish Lakshmanan
