### ISSUE TITLE
Table header texts not visible on Jenkins 2.249+

### ISSUE THREAD

**Issue by fqueiruga** [TobiX/jenkins-neo2-theme#32]
Jenkins 2.249+ introduced changes on the headers (with more fixes on 2.250 and 2.251). The now look like this:

<img width="1316" alt="Captura de pantalla 2020-07-31 a las 9 38 36" src="https://user-images.githubusercontent.com/5738588/89012157-fa920600-d311-11ea-9b54-6cf5e4491062.png">

**Comment by rtm516** [comment]
This was caused by https://github.com/jenkinsci/jenkins/pull/4835 which changed a bunch of css todo with tables/bigtables
