### ISSUE TITLE
Stage Logs overlay has missing background

### ISSUE THREAD

**Issue by viceice** [TobiX/jenkins-neo2-theme#34]
The stage logs dialog has a missing background.
![image](https://user-images.githubusercontent.com/1798109/90369618-67283700-e06c-11ea-985a-dedc26958ccb.png)

![image](https://user-images.githubusercontent.com/1798109/90370052-051c0180-e06d-11ea-934a-f8f4a5406f25.png)

**Comment by TobiX** [comment]
I'm pretty sure this is not a bug of my theme. See https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/87#issuecomment-693155627 for example. Maybe downgrading the pipeline-stage-view until you can upgrade to the next Jenkins LTS?

**Comment by TobiX** [comment]
This is what happens without a theme:
![grafik](https://user-images.githubusercontent.com/78534/93937276-c04c5000-fd27-11ea-9c88-9a480fb8a0e0.png)

**Comment by viceice** [comment]
Thanks, yes, I'm in latest lts now. Seems to be a Jenkins bug.
