### ISSUE TITLE
Log Dialog Background is transparent

### ISSUE THREAD

**Issue by tgdchmi2** [TobiX/jenkins-neo2-theme#36]
Hi TobiX

When opening the Log of a Pipeline Step the background of the opened dialog is transparent:
![image](https://user-images.githubusercontent.com/26160737/94399158-27726600-0167-11eb-90db-72c163017c02.png)

The Problem seems to be the style of '`cbwf-dialog cbwf-stage-logs-dialog`' which leads to a background of: 
* `background-color: var(--background);`

When changing the `background-color` of `cbwf-dialog` to `lighgray` for example it looks good. (using the browsers developer tools)

We are using this URL to include your theme:
* https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css

Could you please check and fix this issue if possible?

Thank you,
Michael

**Comment by TobiX** [comment]
As explained in #34, this is not a theme problem.

**Comment by tgdchmi2** [comment]
Thank you very much and sorry for creating a duplicate. I was so analyzing the issue that I forgot to search for an existing issue...
