### ISSUE TITLE
Back to Dashboard Icon missing

### ISSUE THREAD

**Issue by lajish** [TobiX/jenkins-neo2-theme#4]
Hi there,

**Back to Dashboard** icon is missing. 

Steps
--> Open any Job configuration
--> Observe on left top job menu

![image](https://user-images.githubusercontent.com/6768694/35901191-6cb66b08-0bfb-11e8-850a-96839857f60b.png)

Regs,
Lajish

**Comment by TobiX** [comment]
This is https://github.com/jenkins-contrib-themes/jenkins-core-theme/issues/7 :( - So I probably have to fork  jenkins-contrib-themes ...
