### ISSUE TITLE
Broken animated icon for running jobs

### ISSUE THREAD

**Issue by kjyv** [TobiX/jenkins-neo2-theme#40]
Since Jenkins 2.283 (https://github.com/jenkinsci/jenkins/pull/5065), the animation looks quite weird, an extra arrow circle is rotating around the icon itself.

**Comment by wahammed** [comment]
Is this issue fixed/addressed? I'm facing the same issue.

![image](https://user-images.githubusercontent.com/37405246/113003204-1cd56f80-9190-11eb-9439-35793eeb861d.png)

**Comment by kjyv** [comment]
Doesn't look like any updates have been committed

**Comment by TobiX** [comment]
Yes, I haven't come around to fixing the issue yet. It's not a high priority for me, since I don't use Jenkins weeklies.

**Comment by kjyv** [comment]
Not sure what you're implying but they are not weeklies as in nightlies. They are the normal stable releases including security patches (although released quite often) and they go through all normal release channels, so package managers are updating jenkins to theses versions etc. So it is an issue for all your normal users. And since your theme seems to be the nicest one I'd guess there are quite a few :)

**Comment by iridinite** [comment]
I can confirm that this is a problem on the **stable** release version 2.285. Would love to see a fix!

Incidentally, the new official icons aren't half bad -- could be interesting to reuse parts of it maybe, like the spinning animation?

**Comment by obayit** [comment]
I am also facing the same issue, sadly I had to uninstall the theme because of this.

**Comment by rammie** [comment]
Seeing the same issue.  Would you accept a PR?

**Comment by TobiX** [comment]
Sure, PRs are always welcome!

**Comment by luebbe** [comment]
This is still not 100% fixed. The animated spinner for "not yet run" jobs is wrong:

![grafik](https://user-images.githubusercontent.com/3872576/119811441-6075fc80-bee7-11eb-8820-398e6d210763.png)
job page

![grafik](https://user-images.githubusercontent.com/3872576/119811617-9a470300-bee7-11eb-8b01-26e906fff7c7.png)
plugin update page

**Comment by wahammed** [comment]
![image](https://user-images.githubusercontent.com/37405246/120017447-842e6500-c003-11eb-8029-a43aedeea2aa.png)

This issue is not fixed yet.

**Comment by TobiX** [comment]
PRs welcome.

**Comment by luebbe** [comment]
Maybe @rammie can fix this one too? I tried to figure out the icon's class using FF inspector but didn't have success.

**Comment by wahammed** [comment]
Another observation, This works fine with freestyle or pipeline jobs but not with Multibranch Pipeline.

**Comment by 33man** [comment]
> Another observation, This works fine with freestyle or pipeline jobs but not with Multibranch Pipeline.

Yep I confirm that.

**Comment by tynril** [comment]
It looks like it's also broken with pipeline jobs if they are located in a folder.

**Comment by andytrofimov** [comment]
I'v also submitted a pr to fix animation for all remaining build statuses

**Comment by TobiX** [comment]
The root cause is that https://github.com/TobiX/jenkins-core-theme isn't prepared to work with SVG icons yet and makes some stupid assumptions about Jenkins icons. I'll keep this issue open until I come around to properly fixing all the icons for never Jenkins versions.

**Comment by ksangam** [comment]
Has this been fixed? I see this double rotating icon with LTS version 2.303.2 as well.

**Comment by ybongard** [comment]
> Has this been fixed? I see this double rotating icon with LTS version 2.303.2 as well.

Hmm working here with v0.6

**Comment by 33man** [comment]
> Has this been fixed? I see this double rotating icon with LTS version 2.303.2 as well.

Hmm working here with v0.6

**Comment by virgo47** [comment]
It reappeared when upgrading from 2.347 to 2.349 in our case.
