### ISSUE TITLE
Warning: Couldn't load default plugin "gifsicle"

### ISSUE THREAD

**Issue by lifeofguenter** [TobiX/jenkins-neo2-theme#9]
when running `grunt` I get the following error:

```
 grunt
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "imagemin:dynamic" (imagemin) task
Warning: Couldn't load default plugin "gifsicle" Use --force to continue.
```

goes away after running `npm install gifsicle`

**Comment by TobiX** [comment]
This might have been fixed along the way (maybe by switching to yarn?) - Closing, because I cannot reproduce it.
